version: '3.8'

services:
  mongodb:
    image: mongo:8.0.5
    container_name: mongodb
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - data:/data/db
    networks:
      - mongodb
    restart: always

volumes:
  data:
    driver: local

networks:
  mongodb:
    driver: bridge
